### ISSUE TITLE
Feature request - data forwarding resource

### ISSUE THREAD

**Issue by seansain** [SumoLogic/terraform-provider-sumologic#53] opened 2020-07-24 16:22 UTC
It would be nice to have support in SumoLogic provider for data forwarding so that that it can be setup via IaC instead of manual configuration.

- Transferred from old repo ~ @ Constantin07

**Comment by sumovishal** [comment] 2021-04-29 21:07
Duplicate of #86

**Closed by sumovishal** 2021-04-29 21:07 UTC
