### ISSUE TITLE
Bug: sumologic_folder module always attempts to create folder

### ISSUE THREAD

**Issue by ajbieber** [SumoLogic/terraform-provider-sumologic#266] opened 2021-09-02 20:59 UTC
### Description

Inside my terraform module, I have added the following code that defines a folder in sumo_logic.

```
data "sumologic_personal_folder" "personal_folder" {}

resource "sumologic_folder" "folder" {
  name        = format(var.resource_name_pattern, "folder")
  description = format(var.resource_name_pattern, "folder")
  parent_id   = data.sumologic_personal_folder.personal_folder.id
}
```

When this code was first applied, everything worked as expected. But, as other logic changed in the terraform module and these changes were applied, I began receiving the following error, forcing me to manually delete the folder before preceding. 

```
module.common.sumologic_folder.folder: Creating...

Error: {"id":"V90TP-H2EPX-RR8CY","errors":[{"code":"content:duplicate_content","message":"The content with same name already exists."}]}

  on ../../modules/common/folder.tf line 1, in resource "sumologic_folder" "folder":
   1: resource "sumologic_folder" "folder" {
```

### Expected Behavior

When apply changes to a terraform module and a folder with the same name, description and parent already exists, I would expect no creating, updating, or deleting of the folder to occur

### Environment

- Terraform v0.14.10
- Sumo Logic Terraform Provider v2.9.8

**Comment by seansain** [comment] 2021-09-13 16:46
Hey Austin, any chance you could provide some more info on what type of changes you made to the module that might have caused this? Just looking for a little bit of direction on where to debug why the provider would think it has to create a new folder.

**Comment by ajbieber** [comment] 2021-09-13 17:20
Hi @seansain I'd be happy to provide as much detail as possible. 

Presently, the folder we defined above contains 6 dashboards, with numerous panels defined inside each dashboard. The code below is only a snippet from one of the dashboards due to length of each. Each dashboard has anywhere from 10-20 panels, so the files are fairly lengthy. 

```
variable "parent_folder_id" {
  description = "The ID of the parent folder storing the dashboard"
  type        = string
}

resource "sumologic_dashboard" "lambda_ulm_error_analysis" {
  title       = "AWS Lambda ULM - Error Analysis"
  description = "See an analysis of errors in AWS Lambda."
  folder_id   = var.parent_folder_id
  teme       = "Dark"

  time_range {
    complete_literal_time_range {
      range_name = "yesterday"
    }
  }h

  panel {
    sumo_search_panel {
      key   = "key-error-count-panel"
      title = "Log - Error Count"
      visual_settings = jsonencode(
        {
          "title" : {
            "fontSize" : 16
          },
          "general" : {
            "type" : "svp",
            "displayType" : "default",
            "mode" : "singleValueMetrics"
          },
          "svp" : {
            "option" : "Average",
            "hideLabel" : true,
            "valueFontSize" : 37,
            "noDataString" : "0",
            "rounding" : 0,
            "thresholds" : [
              {
                "from" : 0,
                "to" : 1,
                "color" : "#33CA34"
              },
              {
                "from" : 1,
                "to" : null,
                "color" : "#FF4141"
              }
            ]
          }
        }
      )
      query {
        query_string = format("_sourceCategory = %s *error*\n| count", var.logs_category)
        query_type   = "Logs"
        query_key    = "A"
      }
      time_range {
        begin_bounded_time_range {
          from {
            relative_time_range {
              relative_time = "-1d"
            }
          }
        }
      }
    }
  }

  layout {
    grid {
      layout_structure {
        key = "key-error-count-panel"
        structure = jsonencode(
          {
            "height" : 6,
            "width" : 6,
            "x" : 0,
            "y" : 0
          }
        )
      }
    }
  }
}
```

Defined in a separate module for things "common" to all of the dashboards is the folder. The id of that folder is exported, and is then used as a variable in each of the dashboards as seen above.

```
resource "sumologic_folder" "folder" {
  name        = format(var.resource_name_pattern, "folder")
  description = format(var.resource_name_pattern, "folder")
  parent_id   = data.sumologic_personal_folder.personal_folder.id
}

output "parent_folder_id" {
  value       = sumologic_folder.folder.id
  description = "The ID of the parent folder"
}
```

In one of my earlier updates to this dashboard, I modified the `visual_settings` of the above panel and changed the title font size. Upon running `terraform plan`, the output of the plan specified: "Plan: 7 to add, 0 to change, 0 to destroy." The plan was attempting to recreate the folder and 6 dashboards, and didn't detect any changes.

**Comment by ajbieber** [comment] 2021-12-15 21:00
Hello @seansain, any update on this issue?

**Comment by sumovishal** [comment] 2022-03-24 00:16
@ajbieber sorry for the delayed response. Sean is no longer with Sumo. I am looking into it. 

I am unable to reproduce the issue on my local setup (provider version = `2.13.0`)

1. Here are the files I have in my module
```
.
├── dashboards.tf
├── folders.tf
├── main.tf
├── terraform.tfstate
└── terraform.tfstate.backup
```

2. Contents of `folders.tf`.
```
➜ cat folders.tf 
   1 resource "sumologic_folder" "folder" {
   2   name        = "Test Folder"
   3   description = "Folder description"
   4   parent_id   = data.sumologic_personal_folder.personal_folder.id
   5 }
   6 
   7 output "parent_folder_id" {
   8   value       = sumologic_folder.folder.id
   9   description = "The ID of the parent folder"
  10 }
```
`dashboards.tf` has two dashboards.

3. `terraform apply` followed by `terraform plan` works as expected.
```
➜ terraform apply
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create
...
sumologic_folder.folder: Creating...
sumologic_folder.folder: Creation complete after 0s [id=0000000009B1CE63]
sumologic_dashboard.apache_error_log_analysis: Creating...
sumologic_dashboard.apache_overview: Creating...
sumologic_dashboard.apache_overview: Creation complete after 1s [id=Q4yWe5L0HqtTL1mhMJu4kuDdmSNoqAVezLUx2sx5nucb2e6POHVc3jirTiA6]
sumologic_dashboard.apache_error_log_analysis: Creation complete after 1s [id=jCG7yzE3Xme2ukU4hcZCvs6rnutgoyHK9beA3vn9YTfDioxVy8asKzxw0PBG]

Apply complete! Resources: 3 added, 0 changed, 0 destroyed.

Outputs:

parent_folder_id = "0000000009B1CE63"

➜ terraform plan
sumologic_folder.folder: Refreshing state... [id=0000000009B1CE63]
sumologic_dashboard.apache_error_log_analysis: Refreshing state... [id=jCG7yzE3Xme2ukU4hcZCvs6rnutgoyHK9beA3vn9YTfDioxVy8asKzxw0PBG]
sumologic_dashboard.apache_overview: Refreshing state... [id=Q4yWe5L0HqtTL1mhMJu4kuDdmSNoqAVezLUx2sx5nucb2e6POHVc3jirTiA6]

No changes. Your infrastructure matches the configuration.
```
4. Updated a panel. Modified the panel title, font size, and legend in the `visual_settings`
```
➜ terraform apply
sumologic_folder.folder: Refreshing state... [id=0000000009B1CE63]
sumologic_dashboard.apache_error_log_analysis: Refreshing state... [id=jCG7yzE3Xme2ukU4hcZCvs6rnutgoyHK9beA3vn9YTfDioxVy8asKzxw0PBG]
sumologic_dashboard.apache_overview: Refreshing state... [id=Q4yWe5L0HqtTL1mhMJu4kuDdmSNoqAVezLUx2sx5nucb2e6POHVc3jirTiA6]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # sumologic_dashboard.apache_overview will be updated in-place
  ~ resource "sumologic_dashboard" "apache_overview" {
        id               = "Q4yWe5L0HqtTL1mhMJu4kuDdmSNoqAVezLUx2sx5nucb2e6POHVc3jirTiA6"
        # (5 unchanged attributes hidden)


      ~ panel {
          ~ sumo_search_panel {
              ~ title                                       = "Visitor Locations" -> "Visitor Location"
              ~ visual_settings                             = jsonencode(
                  ~ {
                      ~ legend  = {
                          ~ enabled = false -> true
                        }
                      ~ title   = {
                          ~ fontSize = 14 -> 12
                        }
                        # (3 unchanged elements hidden)
                    }
                )
                # (2 unchanged attributes hidden)

                # (1 unchanged block hidden)
            }
        }


        # (13 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

sumologic_dashboard.apache_overview: Modifying... [id=Q4yWe5L0HqtTL1mhMJu4kuDdmSNoqAVezLUx2sx5nucb2e6POHVc3jirTiA6]
sumologic_dashboard.apache_overview: Modifications complete after 1s [id=Q4yWe5L0HqtTL1mhMJu4kuDdmSNoqAVezLUx2sx5nucb2e6POHVc3jirTiA6]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

5. Subsequent `terraform plan` shows no changes
```
➜ terraform plan
sumologic_folder.folder: Refreshing state... [id=0000000009B1CE63]
sumologic_dashboard.apache_error_log_analysis: Refreshing state... [id=jCG7yzE3Xme2ukU4hcZCvs6rnutgoyHK9beA3vn9YTfDioxVy8asKzxw0PBG]
sumologic_dashboard.apache_overview: Refreshing state... [id=Q4yWe5L0HqtTL1mhMJu4kuDdmSNoqAVezLUx2sx5nucb2e6POHVc3jirTiA6]

No changes. Your infrastructure matches the configuration.
``` 

Can you reproduce this issue consistently? After modifying the dashboard, I would look at terraform state to see what terraform knows about current infrastructure.

**Comment by sumovishal** [comment] 2022-06-25 20:33
Closing this issue as I am unable to reproduce it.

**Closed by sumovishal** 2022-06-25 20:33 UTC
